sudo: false
language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "michaelruocco"
    token:
      secure: "SN4S5T/fgCDYXKUa6GfCAwdaqSDZkpTfmblUZ4jZ8z0TuOuynYGjd/Kk51GeQhC7+OgJk2GemEFiGQVq/G2P4k7GroZfG/tQ4AgGr7EdXkyDgGZxOOHYuKCoudOTsIAMb/ekhvdPdHF5KSCru03m/U7javS5mSwEcf/wUMskqX9RBCh/PuNSUrgHD9o6ddDdrx8mxTHw+9NxgKS8IS6jUT8SOr/u/fts6tyi2WMN7V8dqRnppoaLhbY2PYCP+VDwebwzH8eV8nzsmRmdGTENz3bM+FUQqKxSoOYASVDlNINB4HrNrmmlmY+t6FLlIUZH13Af24e7CRdWDoDXr8j2wxY5HbtgYuebqrEwoi1gfmYQftSxhDoe5hYjXVBcjs1vZsH8HNxYJvABzgl/jkv2EijzDOvTTZJw0ANxCknsh9wOm1ZDOJOCHGMKXo7cqFJgFSvjrctfNAUsg7ikPQsrc2zbGPPRv0ToyS4i9hWobdbo8gWDnvoTNKJO2eRkgi1c2nWXDJSJy7Kn/8TjOruN/NsDpHTnLVBb/6YaaLofYKbtFQBejdmpdnjPl0u8Xo5TSGlrt0D+OlCze/a/AvbXNwo8c6I9qRVV4vEolSXEzL/MG4+8L8eUbrQadw7miaO4Y5zUI+FUueph105Fh2dYYLs3mCgMNRyVBtSLO5ybcYI="

branches:
  except:
    - /^json-masker-*/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r build/reports/jacoco/report.xml

stages:
  - name: build

  - name: snapshot
    if: branch != master

  - name: release
    if: branch = master

jobs:
  include:
    - stage: build
      script: ./gradlew clean spotlessCheck build integrationTest dependencyUpdates jacocoTestReport sonarqube

    - stage: snapshot
      script: ./gradlew artifactoryPublish -Dbuild.number=$TRAVIS_BUILD_NUMBER

    - stage: release
      script:
        - >
          git checkout $TRAVIS_BRANCH;
          ./gradlew release -Prelease.customUsername=$GITHUB_TOKEN;
          ./gradlew bintrayUpload -Dbuild.number=$TRAVIS_BUILD_NUMBER